---
- name: Install Tmux
  when: ansible_distribution == 'Ubuntu'
  include_tasks: file=./apt/vim.yml
  tags:
    - tmux
    - linux

- name: Install Tmux
  include_tasks: file=./brew/vim.yml
  when: ansible_distribution == 'Darwin'
  tags:
    - tmux
    - homebrew
