---
- name: Install Zsh
  when: ansible_os_family == 'Debian'
  include_tasks: file=./apt/zsh.yml
  tags:
    - zsh

- name: Install Zsh
  when: ansible_os_family == 'Darwin'
  include_tasks: file=./brew/zsh.yml
  tags:
    - zsh
