---
- name: Install zsh
  apt: name=zsh
  tags:
    - zsh

- name: Change shell
  shell: chsh -s `which zsh`

- name: Install OhMyZsh
  shell: curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
  tags:
    - ohmyzsh

- name: Install zsh autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - ohmyzsh

- name: Edit zshrc
  shell: sed -i "s/(git/(git zsh-autosuggestions/" ~/.zshrc
  tags:
    - ohmyzsh
